language: node_js
node_js:
  - "12"
dist: xenial
services:
  - xvfb
branches:
  only:
    - master
# before_deploy: cd site && npm install && npm run build
deploy:
  skip_cleanup: true
  provider: pages
  edge: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  local_dir: ./site/dist/
  on:
    branch: master
    # tags: true