language: node_js
os: linux
dist: xenial
node_js:
  - "12"
services:
  - xvfb
addons:
  firefox: latest
  chrome: stable
branches:
  only:
    - master

jobs:
  include:
    - stage: test
      script: npm test
      env:
        - TEST_CASE="p5.js"
      deploy:
        - provider: s3
          edge: true
          endpoint: s3.us-west-002.backblazeb2.com
          acl: public_read
          local_dir: ./results
          glob: "*.json"
          bucket: p5js-benchmark
          on:
            branch: master
            tags: true
    - script: npm test
      env:
        - TEST_CASE="p5.wasm"
    - stage: deploy
      if: (branch = master) AND (tag IS present)
      script: cd site && npm ci && npm run build && cd ..
      deploy:
        - provider: pages
          edge: true
          token: $GITHUB_TOKEN
          local_dir: ./site/dist/
          on:
            branch: master
            tags: true

